### ISSUE TITLE
Consolidate dependencies across requirements.txt and setup.py

### ISSUE THREAD

**Issue by keithing** [civisanalytics/civis-python#190]
I'm paraphrasing some ideas @stephen-hoover had and sent over email:

Repeating dependencies in both setup.py and requirements.txt is problematic.  There are a few solutions to this:

1. remove requirements.txt
2. Replace the contents of requirements.txt with

```
--index-url https://pypi.python.org/simple/

-e .
```
as recommended in [this article](https://caremad.io/posts/2013/07/setup-vs-requirement/).

We should also relax the dependencies in civis-python even further. We should put version requirements in places only where we know we require that version. For example, we require requests>=2.12. But are all of the other strict requirements necessary? I think we could remove the cloudpickle version restrictions entirely, for example. Maybe also for joblib.

**Comment by mheilman** [comment]
I think ideally, we'd follow the best practices described here: https://packaging.python.org/discussions/install-requires-vs-requirements/

That is, we should specify loose, basic requirements in setup.py  and very specific package versions in requirements.txt for reproducibility.

We could perhaps do away with the requirements.txt file entirely and just have a dev-requirements.txt file since the API client is intended to be installed in a variety of different environments.
