### ISSUE TITLE
Asynchronous File Downloads

### ISSUE THREAD

**Issue by gdj0nes** [civisanalytics/civis-python#196]
It would be really nice to have asynchronous file downloads. I came across this because I was using civis_to_multifile_csv which produces multiple files.

**Comment by jacksonllee** [comment]
@gdj0nes `civis_to_multifile_csv` uses [‘PARALLEL ON’ S3 unload](http://civis-python.readthedocs.io/en/v1.7.1/generated/civis.io.civis_to_multifile_csv.html?highlight=civis%20to%20multifile%20csv#civis.io.civis_to_multifile_csv) and blocks until the unload is done. So depending on your use case, if you really want to download and/or work on the individual S3 files concurrently, you could use a thread- or process-based strategy to do so. Since `civis_to_multifile_csv` is normally intended for large tables or queries (for which we'd try to handle in smaller batches and which we don't want/have to download for good reasons), a "download" option isn't baked into this function. (If your table is not large and you'd like to download it, `civis_to_csv` may be an option?)
