### ISSUE TITLE
Incorrect deprecation warning when calling `civis_file_to_table`

### ISSUE THREAD

**Issue by jsfalk** [civisanalytics/civis-python#360]
`file_id` is deprecated only as a named parameter, but the `@deprecate_param` decorator issues a warning whether `file_id` is used as a named parameter or a positional parameter. This also causes invalid warnings when using `dataframe_to_civis` or `csv_to_civis`.

https://github.com/civisanalytics/civis-python/blob/94da3a01ce842a1c42fc585183af2668e3bf928c/civis/io/_tables.py#L877

**Comment by stephen-hoover** [comment]
This warning has been popping up for me too. My suggestion is that you move `file_id` to the end of the parameter list and replace the first positional argument with whatever you want the new name of the parameter to be. Anyone calling the function with `file_id` explicitly named will get the deprecation warning, but there will be no warning for using the argument positionally. Users will also be able to start using the new parameter name if they want to pass parameters by name.

**Comment by mheilman** [comment]
I'd be inclined to just remove the deprecation warning and leave `file_id` as is.

It seems not uncommon for python libraries to have arguments be singular when a single value or list could be provided (e.g., `dtype` for [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)).

Also, if we're concerned about `file_id` being singular, then we'd probably want to rename the function to `civis_files_to_table` also (or add a new one), rather than, say, have `civis_file_to_table` take `file_ids`.

**Comment by stephen-hoover** [comment]
@mheilman , would you accept a PR which removed the deprecation warning and left the code unchanged? Or would you like to continue to move toward a `file_ids` parameter? I could also make a PR for that, along the lines of my last comment.

**Comment by mheilman** [comment]
Yeah, I think we should just remove the deprecation warning. I'd be happy to accept that PR (or let me know if you'd like me to make the PR). Thanks for reminding me about this.
